{% set version = "1.4-0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-sendmailr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/sendmailR_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/sendmailR/sendmailR_{{ version }}.tar.gz
  sha256: 5b8b91fc13f6b07b9fc5a2cf7591cf760fad47c5ea17d87a2891898c506454ad

build:
  merge_build_host: true  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-base64enc
  run:
    - r-base
    - r-base64enc

test:
  commands:
    - $R -e "library('sendmailR')"           # [not win]
    - "\"%R%\" -e \"library('sendmailR')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=sendmailR
  license: GPL-2.0-only
  summary: Package contains a simple SMTP client which provides a portable solution for sending email, including attachment, from within R.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
