{% set version = "1.4-1" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-sendmailr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/sendmailR_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/sendmailR/sendmailR_{{ version }}.tar.gz
  sha256: 2b58147695497d1fbcacff8407b4bb9537362ff452406a2270460e3b930afdd1

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-base64enc
  run:
    - r-base
    - r-base64enc

test:
  commands:
    - $R -e "library('sendmailR')"           # [not win]
    - "\"%R%\" -e \"library('sendmailR')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=sendmailR
  dev_url: https://github.com/olafmersmann/sendmailR
  license: GPL-2.0-only
  summary: Package contains a simple SMTP client with minimal dependencies which provides a portable
    solution for sending email, including file attachments and inline html reports,
    from within R. SMTP Authentication and SSL/STARTTLS is implemented using curl.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
