{% set version = '1.2-1' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-sendmailr
  version: {{ version|replace("-", "_") }}

source:
  fn: sendmailR_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/sendmailR_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/sendmailR/sendmailR_{{ version }}.tar.gz
  sha256: 04feb08c6c763d9c58b2db24b1222febe01e28974eac4fe87670be6fb9bff17c

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 1002
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-base64enc
  run:
    - r-base
    - r-base64enc

test:
  commands:
    - $R -e "library('sendmailR')"           # [not win]
    - "\"%R%\" -e \"library('sendmailR')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=sendmailR
  license: GPL-2
  summary: Package contains a simple SMTP client which provides a portable solution for sending
    email, including attachment, from within R.
  license_family: GPL2
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
