appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: seGtZyvlgLWjlAOEmbXWcBlno7H0jbgFV0hYAjRs1NiZsNprOQalQd3S701ldf8zd129YRTPXV13PNjQrJYIohpcYLFd+0lzs50ZdU0+ip1tS2Q9SZMBCTvYk/Bo4wfVldrcxEWQijQmNGHFMS41f+3EEW+oLNTBXPr36ZCuvU3SRXVB5GkrnEmr7lamGLqsJUFT/whI0u8Sgk9m9jGGKVwKxDm0ORSNzOPIo7if/fGkWfPukRWdd6wElln/p6TrU7+ZBUwvhOU2iPCzuRkxWbtDOYEya68NyXh5+xR7+e+GUTMMLkSb6HVJFWeHSP/cKaMALznW6c0tPouxknEUDsil4/3gTUOfel8PwWWG+Pcyt7sZNvHJH/+NPyx0QSTpEqSCnA3/mZbOqLz/QVAzHEObwCQzaX6az9kMtvhXUZDXONEJgoeuMN7xfMzhghuY5wuX/rINpz+wT9fC9MT6eroCiNo/dfYoRKRRTE5+nH9laMsrHo2zeT3kwMXYA8TjFknLCx7a3cVdr1nPaUTiSSy/L3Giwh1xdDg66nXg2v5VorEI9MADTyeMiPX5nZeA2e1SmL7PCrlzNzpXyN9MdqQbK7Zb9vTaxmGnZXIAfKG1GB+sO68id4xf/8jczZFU6kCnv2Qwrt75wVCd9LITHDUX1KHUtjxkW5qLiWtAx2w=
