travis:
  secure:
    BINSTAR_TOKEN: oucznIE1JGrZvBTtat6JC/CtM7ryQWk5do2RRvzTdcKoL4l+oFPRx+Ja+pKigqbUk43PIWYq62NWmo487+gqp5TiGd7iGDkvcgRCkAyKGpfhD89bXuCxgjvZtUHWh/xU2Se+Mka6OGjWBRxHjt8RcTd6g4YexWd5ROjfGtQIt6Z32NRv5r5PGPPKGAUH5o/yzCCpkmIscAjkXd+GQyEKfgr+m9YbcQJmZ/PiMYJ2w3n2jS76fbC6Tcne7oux25p3gwUmlSU1abfyUAHcSkl2qtExuJ5OjHDPFRdcICnfteig93EcRHrrO/iz6EPzSNaPcLj/KiGC3FgAZg66NAG+dh2DgQd+CLKtSGd6HXTPEMoEDEt6cxNzQyqaeXscnXdsCC0VmffTkDlXbuTwBYL1I8pwbBT4KE+L7BPf/YcsBQV0S/Kk1hYpx4g5SgVp5xEWaSk6wJGC3/TTFwP/rF2Zw8cbRTtOfZh+K6gA+wJP6YaaFZ89qCu61n/fWcd/OC6ySl3HKYKoULQtVHHGiC6fZ/KJbh8ZHaA52e/Q4b5yfnzEM0fadYhB4riXtKtIsCG4B+4S/+vuyXY3q5eLfOKndcQvkWUVGqlfzLozCZBK5FNV+lOzK/FaFmg4zggDFvqFPwc7sAkQRXlXNQapcAZ+tpC7YEYBzMxuyODgPppRHiw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
